setwd("C:/Users/abhilash.s.menon/Downloads/Data Scientist/Codes/exdata-data-household_power_consumption")
data = read.table("household_power_consumption.txt",sep = ";",header = TRUE)
data2<-subset(data,Date =='1/2/2007'| Date == '2/2/2007', select = Date:Sub_metering_3)
data2$DateTime<-paste(data2$Date,data2$Time)
data2<-subset(data2,, select = Global_active_power:DateTime)
data2$DateTime<-strptime(data2$DateTime,"%d/%m/%Y %H:%M:%S")
data2$Global_active_power<-as.numeric(as.character(data2$Global_active_power))
hist(data2$Global_active_power,main = "Global Active Power",xlab = "Global Active Power",col="red")
dev.copy(png,file = "plot1.png")
dev.off()