setwd("C:/Users/abhilash.s.menon/Downloads/Data Scientist/Codes/exdata-data-household_power_consumption")
data = read.table("household_power_consumption.txt",sep = ";",header = TRUE)
data2<-subset(data,Date =='1/2/2007'| Date == '2/2/2007', select = Date:Sub_metering_3)
data2$DateTime<-paste(data2$Date,data2$Time)
data2<-subset(data2,, select = Global_active_power:DateTime)
data2$DateTime<-strptime(data2$DateTime,"%d/%m/%Y %H:%M:%S")
data2$Global_active_power<-as.numeric(as.character(data2$Global_active_power))
data2$Global_reactive_power<-as.numeric(as.character(data2$Global_reactive_power))
data2$Voltage<-as.numeric(as.character(data2$Voltage))
data2$Sub_metering_1<-as.numeric(as.character(data2$Sub_metering_1))
data2$Sub_metering_2<-as.numeric(as.character(data2$Sub_metering_2))
par(mfrow = c(2,2))
with(data2,{
  plot(DateTime,Global_active_power,type = "l",xlab = "",ylab = "Global Active Power")
  plot(DateTime,Voltage,type = "l",xlab = "datetime",ylab = "Voltage")
  plot(DateTime,Sub_metering_1,type = "l",xlab = "",ylab = "Energy sub metering")
  with(data2, lines(DateTime, Sub_metering_2,col="red"))
  with(data2, lines(DateTime, Sub_metering_3,col="blue"))
  legend("topright",pch=1,col = c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
  plot(DateTime,Global_reactive_power,type = "l",xlab = "datetime",ylab = "Global_reactive_power")
})
dev.copy(png,file = "plot4.png")
dev.off()